#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════
# 001-asoundrc-dsnoop-plug
#
# Bird's old install had a bare `pcm.birdash { type dsnoop ... }` in
# .asoundrc — no `plug` wrapper, no softvol layer. The dashboard's
# /api/audio/monitor SSE asks arecord for mono with `-c 1`, which a
# dsnoop slave configured for stereo refuses ("Channel count not
# available"). Result: the "Écoute active" widget showed -∞ dB and
# never animated, even though detections worked fine through the
# recording service.
#
# In parallel, audio_config.json had `device_id = "default"` (the
# pre-dsnoop legacy value), which made the SSE bypass dsnoop entirely
# and conflict with birdengine-recording's exclusive grab on the USB
# hardware.
#
# This migration:
#   1. If ~/.asoundrc has a `pcm.birdash` that does NOT use `type plug`,
#      regenerates it with the layered dsnoop+softvol+plug template
#      (same one install.sh writes for fresh installs since 839409f).
#   2. If audio_config.json has device_id = "default" or missing,
#      sets it to "birdash" and bumps input_channels to match the
#      USB card's actual channel count.
#
# Idempotent: bails out cleanly if .asoundrc is already layered AND
# audio_config.json already points at "birdash".
# ══════════════════════════════════════════════════════════════════════════

set -e

NAME="001-asoundrc-dsnoop-plug"
HOME_DIR="${HOME:-/home/$(whoami)}"
ASOUNDRC="$HOME_DIR/.asoundrc"
REPO_DIR="${BIRDASH_DIR:-$HOME_DIR/birdash}"
AUDIO_CFG="$REPO_DIR/config/audio_config.json"

# ── State probe — exit early if everything is already correct ─────────────

asoundrc_needs_fix=0
audio_cfg_needs_fix=0

if [ -f "$ASOUNDRC" ]; then
    if grep -q "pcm.birdash" "$ASOUNDRC"; then
        # Look for the `type plug` wrapper that the new template uses.
        if ! grep -A2 "pcm.birdash" "$ASOUNDRC" | grep -q "type plug"; then
            asoundrc_needs_fix=1
        fi
    fi
    # else: no pcm.birdash at all → fresh install (no USB mic detected
    # yet, or user manages ALSA themselves). Don't touch.
fi

if [ -f "$AUDIO_CFG" ]; then
    dev_id=$(python3 -c "import json; print(json.load(open('$AUDIO_CFG')).get('device_id',''))" 2>/dev/null || echo "")
    if [ "$dev_id" = "default" ] || [ -z "$dev_id" ]; then
        # Only flag for migration if there IS actually a USB capture card
        # to point to. On a Pi with no mic, "default" is the right answer.
        if arecord -l 2>/dev/null | grep -q "USB"; then
            audio_cfg_needs_fix=1
        fi
    fi
fi

if [ "$asoundrc_needs_fix" = "0" ] && [ "$audio_cfg_needs_fix" = "0" ]; then
    echo "[migrate $NAME] already applied"
    exit 0
fi

# ── Detect the USB card so we know what to put in the dsnoop slave ────────

USB_CARD=$(arecord -l 2>/dev/null | grep -oP 'card \K\d+(?=:.*USB)' | head -1)
USB_CARD_NAME=$(arecord -l 2>/dev/null | grep -oP "card $USB_CARD: \K\w+" | head -1)
USB_CHANNELS=$(arecord -l 2>/dev/null | grep "card $USB_CARD:" -A1 | head -1 | grep -oP '\d+ ch' | grep -oP '\d+' | head -1)
[ -z "$USB_CHANNELS" ] && USB_CHANNELS=2  # safe default for most USB mics

if [ -z "$USB_CARD" ] || [ -z "$USB_CARD_NAME" ]; then
    echo "[migrate $NAME] no USB card detected — leaving setup alone"
    exit 0
fi

# ── 1. Rewrite .asoundrc with the layered template ────────────────────────

if [ "$asoundrc_needs_fix" = "1" ]; then
    cp "$ASOUNDRC" "$ASOUNDRC.before-$NAME"
    cat > "$ASOUNDRC" <<ASOUND
# Auto-generated by Birdash for $USB_CARD_NAME
# Migrated by $NAME on $(date -Iseconds)
pcm.dsnooper {
    type dsnoop
    ipc_key 2048
    ipc_key_add_uid false
    ipc_perm 0666
    slave {
        pcm "hw:CARD=$USB_CARD_NAME,DEV=0"
        channels $USB_CHANNELS
        rate 48000
        format S16_LE
        period_size 1024
        buffer_size 8192
    }
}
pcm.boosted {
    type softvol
    slave.pcm "dsnooper"
    control { name "Boost"; card $USB_CARD_NAME; }
    min_dB -5.0
    max_dB 30.0
}
pcm.birdash {
    type plug
    slave.pcm "boosted"
}
ASOUND
    echo "[migrate $NAME] rewrote .asoundrc with dsnoop+softvol+plug (backup: .asoundrc.before-$NAME)"
fi

# ── 2. Fix audio_config.json device_id and input_channels ─────────────────

if [ "$audio_cfg_needs_fix" = "1" ]; then
    cp "$AUDIO_CFG" "$AUDIO_CFG.before-$NAME"
    python3 - "$AUDIO_CFG" "$USB_CHANNELS" "$USB_CARD_NAME" <<'PY'
import json, sys
path, ch, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
with open(path) as f:
    d = json.load(f)
d['device_id'] = 'birdash'
if not d.get('device_name') or d['device_name'] == 'Auto-detect':
    d['device_name'] = f'{name} (dsnoop)'
d['input_channels'] = ch
with open(path, 'w') as f:
    json.dump(d, f, indent=2)
PY
    echo "[migrate $NAME] audio_config.json: device_id=birdash, input_channels=$USB_CHANNELS (backup: $(basename $AUDIO_CFG).before-$NAME)"
fi

# ── 3. Reload services so the new ALSA layout and config take effect ──────
# Don't fail the migration if this errors — update.sh handles its own
# restart pass right after migrations run, and the user always has
# `sudo systemctl restart birdash birdengine-recording` as a fallback.

if [ "$asoundrc_needs_fix" = "1" ] || [ "$audio_cfg_needs_fix" = "1" ]; then
    sudo systemctl restart birdengine-recording 2>/dev/null || true
fi

echo "[migrate $NAME] done"
